"""add_indexes_and_unique_constraint_to_attempts

Revision ID: 435bd5d856f8
Revises: 5b06a4b3c19a
Create Date: 2026-08-07 04:01:06.092373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435bd5d856f8'
down_revision: Union[str, None] = '5b06a4b3c19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_active_attempt_unique', 'attempts', ['user_id', 'quiz_id'], unique=True, postgresql_where=sa.text("status = 'IN_PROGRESS'"))
    op.create_index(op.f('ix_attempts_status'), 'attempts', ['status'], unique=False)
    op.create_index(op.f('ix_attempts_submitted_at'), 'attempts', ['submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempts_submitted_at'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_status'), table_name='attempts')
    op.drop_index('ix_active_attempt_unique', table_name='attempts', postgresql_where=sa.text("status = 'IN_PROGRESS'"))
    # ### end Alembic commands ###
