"""create_attempt_tables

Revision ID: 9c70dfc75a91
Revises: 9c90a53e46fd
Create Date: 2026-08-07 03:56:14.411201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c70dfc75a91'
down_revision: Union[str, None] = '9c90a53e46fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('quiz_version', sa.Integer(), nullable=False),
    sa.Column('quiz_title', sa.String(length=100), nullable=False),
    sa.Column('passing_percentage', sa.Integer(), nullable=False),
    sa.Column('negative_marking', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', 'AUTO_SUBMITTED', name='attempt_status'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('incorrect_answers', sa.Integer(), nullable=False),
    sa.Column('unanswered_answers', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('random_seed', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_attempts_quiz_id_quizzes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attempts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts'))
    )
    op.create_index(op.f('ix_attempts_quiz_id'), 'attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)
    op.create_table('attempt_questions',
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sa.String(length=1000), nullable=False),
    sa.Column('explanation', sa.String(length=1000), nullable=True),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], name=op.f('fk_attempt_questions_attempt_id_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_attempt_questions_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempt_questions'))
    )
    op.create_index(op.f('ix_attempt_questions_attempt_id'), 'attempt_questions', ['attempt_id'], unique=False)
    op.create_table('attempt_options',
    sa.Column('attempt_question_id', sa.Uuid(), nullable=False),
    sa.Column('option_id', sa.Uuid(), nullable=False),
    sa.Column('option_text', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_question_id'], ['attempt_questions.id'], name=op.f('fk_attempt_options_attempt_question_id_attempt_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], name=op.f('fk_attempt_options_option_id_options')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempt_options'))
    )
    op.create_index(op.f('ix_attempt_options_attempt_question_id'), 'attempt_options', ['attempt_question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempt_options_attempt_question_id'), table_name='attempt_options')
    op.drop_table('attempt_options')
    op.drop_index(op.f('ix_attempt_questions_attempt_id'), table_name='attempt_questions')
    op.drop_table('attempt_questions')
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_quiz_id'), table_name='attempts')
    op.drop_table('attempts')
    # ### end Alembic commands ###
