"""add_slugs_and_lifecycle_timestamps

Revision ID: b7736387dee7
Revises: 633693b57781
Create Date: 2026-08-07 03:50:00.963111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7736387dee7'
down_revision: Union[str, None] = '633693b57781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(length=60), nullable=False))
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.add_column('quizzes', sa.Column('slug', sa.String(length=120), nullable=False))
    op.add_column('quizzes', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quizzes', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_quizzes_slug'), 'quizzes', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quizzes_slug'), table_name='quizzes')
    op.drop_column('quizzes', 'archived_at')
    op.drop_column('quizzes', 'published_at')
    op.drop_column('quizzes', 'slug')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
